---
- hosts: postgresql-nodes
  become: yes

  pre_tasks:
    - name: "Instalar dnf"
      yum: "name={{ item }} state=present"
      with_items:
        - dnf

    - name: "Instalar paquetes necesarios"
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server
        - python3
        - python
        - python3-devel
        - python3-devel
        - postgresql-devel

    - name: "Reinstalar epel-release"
      shell: sudo yum reinstall -y  epel-release

    - name: "Instalar paquetes de Python"
      yum: "name={{ item }} state=present"
      with_items:
        - python-psycopg2