---
- hosts: postgresql-nodes
  become: yes

  pre_tasks:
    - name: "Instalar paquetes necesarios"
      dnf: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server
        - python3
        - python
        - python3-devel
        - python3-devel
        - postgresql-devel

    - name: "Repositorio 1"
      shell: sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E '%{rhel}').noarch.$

    - name: "Reinstalar epel-release"
      shell: sudo yum reinstall -y  epel-release

    - name: "Reinstalar python"
      shell: sudo yum reinstall -y python-pip

    - name: "Repositorio 2"
      shell: sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-l$

    - name: "Instalar paquetes de Python"
      yum: "name={{ item }} state=present"
      with_items:
        - python-psycopg2