---
- hosts: postgresql-nodes
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "Conceder permisos a file.sql"
      shell: sudo chmod -R a+rwX /tmp/prueba.sql

    - name: "Importar datos a la base de datos desde un .sql"
      become: true
      become_user: postgres
      shell: psql {{ db_name }} < /tmp/prueba.sql

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted