---
- hosts: node1
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "Copiar archivo .sql al servidor"
      copy:
        src: "{{ file }}/nombrearchivo.sql"
        dest: "{{ dest }}"

    - name: "Conceder permisos al archivo .sql"
      shell: sudo chmod -R a+rwX /tmp/nombrearchivo.sql

    - name: "Importar datos a la base de datos desde el archivo .sql"
      become: true
      become_user: postgres
      shell: psql {{ db_name }} < /tmp/nombrearchivo.sql
